name: ci

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:

  build:
    name: build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: test go get
      run: go get -v github.com/robtec/ppr-go/cmd/...

    - name: Build
      run: make build
    
    - name: release-linux-x64
      uses: ngs/go-release.action@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        GOARCH: "amd64"
        GOOS: linux
        CMD_PATH: "cmd/ppr/main.go"

    - name: release-windows-x64
      uses: ngs/go-release.action@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        GOARCH: "amd64"
        GOOS: windows
        CMD_PATH: "cmd/ppr/main.go"
