on:
  release:
    types: [published]

name: cd
jobs:
  release-linux-amd64:
    name: linux64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build and push
      uses: robtec/go-release.action@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        GOARCH: amd64
        GOOS: linux
        CMD_PATH: "./cmd/ppr"